FIAP.Portal/Models/ErrorViewModel.cs
using System;

namespace FIAP.Portal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FIAP.Portal/Controllers/BaseController.cs
using FIAP.Core.Infra.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FIAP.Portal.Controllers
{
    public class BaseController : Controller
    {
        internal IConfiguration _config;
        internal IApiCaller _apiCaller;
        public BaseController(IConfiguration config, IApiCaller apiCaller) : base()
        {
            _config = config;
            _apiCaller = apiCaller;
        }
    }
}

FIAP.Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FIAP.Portal.Models;

namespace FIAP.Portal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FIAP.Portal/Controllers/ParceriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using FIAP.Core.Infra.Interface;
using FIAP.Parceria.Services.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace FIAP.Portal.Controllers
{
    public class ParceriaController : BaseController
    {
        public ParceriaController(IConfiguration configuration, IApiCaller apiCaller) : base(configuration, apiCaller)
        {
        }

        // GET: Parceria
        public async Task<IActionResult> Index()
        {
            IEnumerable<Parceria.Models.Parceria> result;
            try
            {
                result = await _apiCaller.GetAsync<IEnumerable<Parceria.Models.Parceria>>(_config.GetConnectionString("API"), "/Parceria");
            }
            catch (Exception)
            {
                result = Enumerable.Empty<Parceria.Models.Parceria>();
            }

            return View(result);
        }

        // GET: Parceria/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Parceria/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm]Parceria.Models.Parceria parceria)
        {
            try
            {
                await _apiCaller.Post<Parceria.Models.Parceria>(parceria,
                    _config.GetConnectionString("API"), "/Parceria");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Parceria/Edit/5
        public async Task<IActionResult> Edit(int codigo)
        {
            var parceria = await _apiCaller.GetAsync<Parceria.Models.Parceria>(_config.GetConnectionString("API"),
                $"/Parceria/{codigo}");
            return View(parceria);
        }

        // POST: Parceria/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm]Parceria.Models.Parceria parceria)
        {
            try
            {
                var result = await _apiCaller.Put<Parceria.Models.Parceria>(parceria,
                        _config.GetConnectionString("API"), $"/Parceria/{parceria.Codigo}");

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Parceria/Delete/5
        public async Task<IActionResult> Delete(int codigo)
        {
            try
            {
                var result = await _apiCaller.Delete<Parceria.Models.Parceria>(_config.GetConnectionString("API"), $"/Parceria/{codigo}");

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FIAP.Portal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FIAP.Portal/Views/Parceria/Create.cshtml
@model FIAP.Parceria.Models.Parceria

@{
    ViewData["Title"] = "View";
}

<h1>Cadastrar parceria</h1>

<h4>Parceria</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Empresa" class="control-label"></label>
                <input asp-for="Empresa" class="form-control" />
                <span asp-validation-for="Empresa" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="DataTermino" class="control-label"></label>
                <input asp-for="DataTermino" class="form-control" />
                <span asp-validation-for="DataTermino" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="URLPagina" class="control-label"></label>
                <input asp-for="URLPagina" class="form-control" />
                <span asp-validation-for="URLPagina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FIAP.Portal/Views/Parceria/Edit.cshtml
@model FIAP.Parceria.Models.Parceria

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Parceria</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Codigo" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Empresa" class="control-label"></label>
                <input asp-for="Empresa" class="form-control" />
                <span asp-validation-for="Empresa" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="DataTermino" class="control-label"></label>
                <input asp-for="DataTermino" class="form-control" />
                <span asp-validation-for="DataTermino" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="URLPagina" class="control-label"></label>
                <input asp-for="URLPagina" class="form-control" />
                <span asp-validation-for="URLPagina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FIAP.Portal/Views/Parceria/index.cshtml
@model IEnumerable<FIAP.Parceria.Models.Parceria>
@{
    ViewData["Title"] = "index";
}

<h1>Controle de parcerias</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Titulo</th>
                <th>Empresa</th>
                <th>Data Inicio</th>
                <th>Data de término</th>
                <th>Qtd. Likes</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Codigo</td>

                    <td>@item.Titulo</td>

                    <td>@item.Empresa</td>

                    <td>@item.DataInicio</td>

                    <td>@item.DataTermino</td>

                    <td>@item.QtdLikes</td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new {codigo = item.Codigo }) |
                        @Html.ActionLink("Delete", "Delete", new { codigo = item.Codigo })
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>  

FIAP.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FIAP.Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FIAP.Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parceria" asp-action="Index">Parceria</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FIAP.Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>